
#2.x版本中由于引入了不同客户端，需要指定配置哪种连接池
#jedis客户端
spring:
  session:
    store-type: redis
    redis:
      namespace: client1
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    database: 3
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
server:
  port: 8081
  session:
    timeout: 1800